service: import-service

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: eu-west-1
  iamRoleStatements:
    - Effect: Allow
      Action: s3:*
      Resource: arn:aws:s3:::products-upload-s3
    - Effect: Allow
      Action: sqs:*
      Resource: arn:aws:sqs:eu-west-1:581741678738:catalog-items-queue

plugins:
  - serverless-webpack

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: true
    packager: npm

functions:
  importProductsFile:
    handler: src/handler.importProductsFile
    events:
      - http:
          path: import
          method: get
          cors: false
          request:
            parameters:
              querystrings:
                name: true
  importFileParser:
    handler: src/handler.importFileParser
    events:
      - s3:
          bucket: products-upload-s3
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
          existing: true
